# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73d11e2eab1bc6c19fae119b674a2d99af6d69381cef6e2fc5b0504a5fcc1824df03bc9c2304c5eea4481e5d2f25bffba6b98725e8559ee578bc94e355e79d78

test:
  secret_key_base: 3043b3ea407c08653db7509a27a2cce3812393cb6b56503bf26e7807cc77e4469d5bb4be9e715b66b42189ac662bcc5686bec5781213ea64efbcceb8bdf942e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
